---
env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
root: true
rules: {}
overrides:
  - env:
      browser: true
      es6: true
      node: true
    extends:
      - "eslint:recommended"
      - "plugin:@typescript-eslint/eslint-recommended"
      - "plugin:@typescript-eslint/recommended"
      - "prettier/@typescript-eslint"
    files:
      - "**/*.ts"
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
      - eslint-plugin-tsdoc
    rules:
      tsdoc/syntax: warn
